// Parse the grades 5-6 section of the UIL 2025-2026 A+ Spelling list text.
// Input: /tmp/grade56.txt (pdftotext -layout output)
// Output: words.json (array of { n, entry, accepted[], hint, caseSensitive })
const fs = require('fs');
const raw = fs.readFileSync('C:\\Users\\David\\AppData\\Local\\Temp\\grade56.txt', 'utf8');

// The pdftotext output has up to 3 columns per line with entries like
//   "123. word"  or  "45.  word"  or  "1.   word with space"
// We match every "<num>. <text>" occurrence and cut off at the next
// "<num2>." or end-of-line/column gap.

const re = /(\d{1,3})\.\s+([^\n]+?)(?=\s{2,}\d{1,3}\.|\s*$)/g;
const seen = new Map(); // n -> raw string

for (const line of raw.split(/\r?\n/)) {
  // Strip header labels inline — some rows mix the page header with the first column entry.
  let cleaned = line
    .replace(/Grades 5-6 \(cont'd\)/gi, '')
    .replace(/Grades 5-6/gi, '')
    .replace(/UIL A\+ Spelling Word List 2025-2026/gi, '')
    .replace(/Page \d+/gi, '');
  if (!cleaned.trim()) continue;
  let m;
  re.lastIndex = 0;
  while ((m = re.exec(cleaned)) !== null) {
    const n = parseInt(m[1], 10);
    if (n < 1 || n > 800) continue;
    const text = m[2].trim().replace(/\s+/g, ' ');
    if (!text) continue;
    // Prefer first occurrence; continuations on later lines are rare here.
    if (!seen.has(n)) seen.set(n, text);
  }
}

// Build structured entries
const entries = [];
for (let i = 1; i <= 800; i++) {
  if (!seen.has(i)) {
    console.error(`MISSING #${i}`);
    continue;
  }
  let entry = seen.get(i);
  // Extract parenthetical hint, e.g. "boulder (rock)" or "yippee (delight)" or "deepwater (adj.)"
  let hint = null;
  const hintMatch = entry.match(/\s*\(([^)]+)\)\s*$/);
  if (hintMatch) {
    hint = hintMatch[1].trim();
    entry = entry.replace(/\s*\([^)]+\)\s*$/, '').trim();
  }
  // Split alternates on commas: "bandanna, bandana" -> ["bandanna", "bandana"]
  const accepted = entry.split(/,\s*/).map(s => s.trim()).filter(Boolean);
  const caseSensitive = accepted.some(w => /[A-Z]/.test(w));
  entries.push({ n: i, display: entry, accepted, hint, caseSensitive });
}

const outDir = 'C:\\Users\\David\\Documents\\local-only code\\uil-speller';
fs.writeFileSync(outDir + '\\words.json', JSON.stringify(entries, null, 2));
fs.writeFileSync(
  outDir + '\\words.js',
  '// Auto-generated by scripts/parse_wordlist.js. Do not edit by hand.\n' +
  'window.WORDS = ' + JSON.stringify(entries) + ';\n'
);
console.log(`Wrote ${entries.length} entries to words.json + words.js`);
